#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

$basePath = dirname(__DIR__);

$app = require_once "$basePath/bootstrap/app.php";

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(new Symfony\Component\Console\Input\ArgvInput, new Symfony\Component\Console\Output\ConsoleOutput));
