<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->title }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .page-break {
            page-break-after: always;
        }
        .cover {
            text-align: center;
            padding: 100px 40px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            display: flex;
            flex-direction: column;
            justify-content: center;
            min-height: 100vh;
        }
        .cover h1 {
            font-size: 48px;
            margin-bottom: 20px;
        }
        .cover p {
            font-size: 18px;
            margin-bottom: 30px;
            opacity: 0.9;
        }
        .toc {
            padding: 40px;
            page-break-after: always;
        }
        .toc h2 {
            margin-bottom: 20px;
            color: #667eea;
        }
        .toc-item {
            margin: 10px 0;
            padding-left: 20px;
        }
        .content {
            padding: 40px;
        }
        .section {
            margin-bottom: 40px;
        }
        .section h2 {
            color: #667eea;
            font-size: 28px;
            margin-bottom: 20px;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }
        .section p {
            margin-bottom: 15px;
            text-align: justify;
        }
        .section img {
            max-width: 100%;
            height: auto;
            margin: 20px 0;
            border-radius: 8px;
        }
        .footer {
            text-align: center;
            padding: 20px;
            font-size: 12px;
            color: #999;
            border-top: 1px solid #ddd;
            margin-top: 30px;
        }
    </style>
</head>
<body>
    <!-- Cover Page -->
    <div class="cover page-break">
        <h1>{{ $report->title }}</h1>
        <p>{{ $report->subject }}</p>
        <p style="margin-top: 50px; font-size: 14px;">Generated by Texts to Book</p>
        <p style="font-size: 12px;">{{ now()->format('F j, Y') }}</p>
    </div>

    <!-- Table of Contents -->
    <div class="toc">
        <h2>Table of Contents</h2>
        @foreach($sections as $index => $section)
            <div class="toc-item">{{ $index + 1 }}. {{ $section->title }}</div>
        @endforeach
    </div>

    <!-- Content -->
    <div class="content">
        @foreach($sections as $index => $section)
            <div class="section page-break">
                <h2>{{ $index + 1 }}. {{ $section->title }}</h2>

                @foreach($section->images as $image)
                    <img src="{{ $image->image_url }}" alt="{{ $image->prompt }}">
                @endforeach

                <div style="white-space: pre-wrap;">{{ $section->content }}</div>
            </div>
        @endforeach
    </div>

    <!-- Footer -->
    <div class="footer">
        <p>This document was generated by Texts to Book on {{ now()->format('F j, Y \a\t g:i A') }}</p>
    </div>
</body>
</html>
